Gg conference webpage
tinatsina/tinatsina-capstone pull request #1
Opened 2022-07-27 18:40 UTC by tinatsina

# Microverse Capstone Project

- first submission of capstone project
- used HTML, CSS, JS linters
- created dynamic JS webpages
- All links to other websites fully functional
- no merger conflicts

2022-07-27 20:07 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @tinatsina,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-27 20:07 UTC, topeogunleye commented on scripts/dynamicData.js
> +const dataBank = speakerPanel.map((speaker) => `
- [ ] As written in the project requirements. Please kindly surround your iterative function here with a `windows.onload`function because it'll make sure the function waits for the rest of the page to load. 


See [here](https://stackoverflow.com/questions/20180251/when-to-use-window-onload) for more info:

2022-07-28 00:41 UTC, tinatsina commented on README.md
> +
## Resolved 👍 
- used your advice and added the video I made
- The video was made using LOOM
- Thanks for the assist

2022-07-28 00:44 UTC, tinatsina commented on pages/about.html
> +              <li><a href="pages/about.html">About</a></li>
## Resolved 👍 
- changed the link of the anchor to point correctly
- used your recommended format

2022-07-28 00:50 UTC, tinatsina commented on styles/mobile.css
> +  background-color: var(--red-color);
## Resolved 😅 
- updated the colors from the variables
- used a new color combination
- `--nav-color: #f7f4f4`
- matches with the header area color perfectly
- Thanks for assisting

2022-07-28 01:02 UTC, tinatsina commented on index.html
> +                <h1 class="header-time">2015.10.15(THU) ~ 16(FRI)</h1>
## Resolved 👌 

- used your semantic tag advice
- changed all `h1` to `h2` tags
- only one h1 tag remains
- thanks for the remainder ❤️

2022-07-28 01:03 UTC, tinatsina commented on pages/about.html
> +                <h1 class="main-program-header second-header">
## Resolved 👌 

- used your semantic tag advice
- changed all `h1` to `h2` tags
- only one h1 tag remains
- thanks for the remainder ❤️ 
- done for both `index.html` and `about.html`

2022-07-28 01:37 UTC, tinatsina commented on scripts/dynamicData.js
> +const dataBank = speakerPanel.map((speaker) => `
## Resolved 💪 

- used your advice and added the `DOMContentLoaded` function
- now the values are fed only when the page fully loads
- Thanks again

![Thor Shoulders](https://media.giphy.com/media/EfsqyinraWHCKWxsjq/giphy.gif)

2022-07-28 02:12 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/93039359/178569876-9fcda5e8-6819-4569-95ee-acb393903a05.jpg)

### Hey @tinatsina :wave:

### Highlights :1st_place_medal:
 
:heavy_check_mark: Descriptive PR title
:heavy_check_mark: Descriptive PR summary
:heavy_check_mark: Descriptive Branch name
:heavy_check_mark: Following Linters
:heavy_check_mark: Following Github Flow

Good job on implementing some of the changes required by the previous reviewer, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:


# Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-28 02:12 UTC, HAMMAS-SALEEM commented on index.html
> +        </div>
- [ ] Please use `h3` instead of `h2` because you are already using an `h2` as the main heading of this page and to follow Heading Hierarchy :blush:

2022-07-28 02:12 UTC, HAMMAS-SALEEM commented on index.html
> +                <li><a href="#" class="anchor-navbar">Piltover</a></li>
### Your Design
![your-design (copy)](https://user-images.githubusercontent.com/93039359/181405059-b25f76df-58e5-460d-986b-740443dfa452.png)

### Cindy Shin Design
![navigation](https://user-images.githubusercontent.com/93039359/181404615-58696d31-a0e4-4bdd-a734-7f8b932c345d.png)


**[Optional]**
- [ ] Your design is good but it is not following the Cindy Shin Design. You have two About links the top About link is working but this is not the place of your about link. Please use the second About link to redirect your page to the about page. Then your project will look professional and will attract the recruiters in future :+1:

2022-07-28 03:11 UTC, tinatsina commented on index.html
> +                <li><a href="#" class="anchor-navbar">Piltover</a></li>
## Resolved 😸 

- used the `href` attribute to locate corresponding `id`
- now all links work, except decorative ones
- Thanks

2022-07-28 03:21 UTC, tinatsina commented on index.html
> +        </div>
## Resolved 👍 

- used your advice on [Heading Hierachy](https://www.w3.org/WAI/test-evaluate/preliminary/#headings)
- Now using the correct flow of `h1` `h2` `h3` tags
- Improved semantics for the project
- Thanks for the assist

2022-07-28 03:36 UTC, tinatsina commented on index.html
> +                <li><a href="#" class="anchor-navbar">Piltover</a></li>
## Resolved 👌 
- used your advice and updated the links
- Also used your preferences and left only one `about` link
- Both pages now have that issue resolved
- Thanks for the assist

![Lets Do This Thing](https://media.giphy.com/media/8y8NVqFqhTQVa/giphy.gif)

2022-07-28 03:47 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)
Hey @tinatsina :wave:

Great work on implementing the requested changes. Your project is complete. There is nothing else to say about your project. :+1:
Go ahead and merge it. :muscle:

## Highlights :1st_place_medal:
:heavy_check_mark: Following GitFlow
:heavy_check_mark: Following Linters
:heavy_check_mark: Following the Design

### [Optional]

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-28 04:04 UTC, HAMMAS-SALEEM reviewed
## Congratulations on completing your Capstone Project :tada: :partying_face:

2022-08-05 11:13 UTC, merged